### ISSUE TITLE
Google Chrome: sound out: nothing audible

### ISSUE THREAD

**Issue by grahamperrin** [mrclksr/linux-browser-installer#2]
I get video playback at pages such as https://www.itv.com/hub/itv (sign in required) and https://www.ted.com/talks/james_geary_metaphorically_speaking but no sound. 

[audio/virtual_oss](https://www.freshports.org/audio/virtual_oss/) in use, if that's relevant. From my `rc.conf`:

```text
virtual_oss_enable="YES"
virtual_oss_default_args="\
  -T /dev/sndstat \
  -S \
  -i 8 \
  -C 2 -c 2 \
  -r 48000 \
  -b 24 \
  -s 8.0ms \
  -f /dev/dsp1 \
  -c 2 \
  -d dsp \
  -t vdsp.ctl"
sndiod_enable="YES"
```
```text
root@mowa219-gjp4-8570p:~ # uname -v
FreeBSD 13.0-CURRENT #72 r367936: Sun Nov 22 21:46:00 GMT 2020     root@mowa219-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
```

**Comment by grahamperrin** [comment]
… ah, is this the answer?

https://forums.FreeBSD.org/threads/linuxulator-how-to-run-google-chrome-linux-binary-on-freebsd.77559/post-484339

> … tell pulseaudio clients where to find sound by setting the socket path via the `PULSE_SERVER` environment variable …

**Comment by mrclksr** [comment]
Hi @grahamperrin ,

does the sound work with the wrapper?

> which, incidentally, explains why /usr/local/bin/chrome no longer runs Chromium for me; I'm not quite ready to abandon Chromium :-)

Sorry about that :-). I've changed the names, so that the wrapper and desktop files now have the prefix *linux-*.

**Comment by grahamperrin** [comment]
As _root_, this morning: 

```text
pkg remove chromium && pkg install chromium
cd /usr/home/grahamperrin/Downloads/linux-browser-installer/
git pull
./linux-browser-installer deinstall chrome && ./linux-browser-installer install chrome
```

– after which, as _grahamperrin_, the Ted Talk content was audible first in Google Chrome, then in Chromium: 

`/compat/ubuntu/bin/chrome https://www.ted.com/talks/james_geary_metaphorically_speaking ; chrome https://www.ted.com/talks/james_geary_metaphorically_speaking`

Also audible, ITV Hub content: 

`/compat/ubuntu/bin/chrome https://www.itv.com/hub/itv`

### Bonus

Re: <https://forums.freebsd.org/threads/linuxulator-how-to-run-google-chrome-linux-binary-on-freebsd.77559/post-485731>, [Open With](https://github.com/darktrojan/openwith/#readme) now works as expected.
