### ISSUE TITLE
Ubuntu 22.10 Support

### ISSUE THREAD

**Issue by Sejoslaw** [mrclksr/linux-browser-installer#27]
Hi,

I've tried to install Ubuntu's "kinetic" version (22.10 technically) and I'd receive an error as shown below:

![image](https://user-images.githubusercontent.com/13147684/198555853-136044da-5c1a-4015-bfa7-6f82466c8a89.png)

![image](https://user-images.githubusercontent.com/13147684/198556221-481cf29b-bee1-47ef-863e-fa15f8a1db4e.png)

Is it possible to force script to install newer Ubuntu version ?

**Comment by mrclksr** [comment]
Hi @Sejoslaw,

check the version  of the `ld` library under `/compat/ubuntu/lib/x86_64-linux-gnu/`, and adjust the content of the `ld_version` variable in `linux-browser-installer` accordingly. Then remove the chroot and try again.

**Comment by Sejoslaw** [comment]
Thanks for your advice ^^

I've checked the versions and configured it accordingly (checked on Ubuntu 22.10 VM)

![image](https://user-images.githubusercontent.com/13147684/198574103-edd4154d-b7d3-4611-b630-4b0c6b2c8f5f.png)

Added the repo

![image](https://user-images.githubusercontent.com/13147684/198574739-c486a914-1a7d-4f14-8404-6f78e5f428d7.png)

deb http://archive.ubuntu.com/ubuntu/ kinetic main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ kinetic-updates main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu/ kinetic-security main restricted universe multiverse

Ran -> apt update && apt dist-upgrade
(everything updated as it should)

And still got the same error as shown below (ld version was ran from inside on Ubuntu)

![image](https://user-images.githubusercontent.com/13147684/198579860-1eb060ea-1bf8-4349-9da4-64632063815d.png)

**Comment by Sejoslaw** [comment]
I will try with removing everything

**Comment by Sejoslaw** [comment]
No luck

![image](https://user-images.githubusercontent.com/13147684/198582307-ffa858e8-7558-4c92-bb70-e6ee5a0d65e3.png)

**Comment by mrclksr** [comment]
Alright, found the problem. Change the `fix_ld_path()` function to:

```
fix_ld_path()
{
        cp ${chroot_path}/lib/x86_64-linux-gnu/ld-* \
                ${chroot_path}/lib64/ld-linux-x86-64.so.2
}
```

Then:

```
# ./linux-browser-installer chroot delete
# ./linux-browser-installer chroot create
```

**Comment by Sejoslaw** [comment]
FYI
Chroot login worked

![image](https://user-images.githubusercontent.com/13147684/198637949-a7112479-915b-476c-bc43-0919397eafdd.png)

**Comment by mrclksr** [comment]
Sorry, the above code didn't work as expected if the target is a symbolic link. Fixed that.
The latest commit should do the job. I tested it with focal and kinetic.

**Comment by Sejoslaw** [comment]
Tested with combination like so:

chroot delete
chroot create
install chrome

And receive (menu-item is working as expected - thanks ^^) an error.
The below screen shows what is happening when I try to upgrade Ubuntu itself.
(This might be an issue with Ubuntu itself)

![image](https://user-images.githubusercontent.com/13147684/198656438-d6ea0981-511e-4c76-9549-e3d2056bf20f.png)

**Comment by mrclksr** [comment]
> (This might be an issue with Ubuntu itself)

It seems to be the case.

**Comment by Sejoslaw** [comment]
Ok
Thank you for help and updates ^^
Great job!

**Comment by mrclksr** [comment]
Thank you for opening the issue. It made the script better :)
