### ISSUE TITLE
ELF interpreter /lib64/ld-linux-x86-64.so.2 not found, error 2

### ISSUE THREAD

**Issue by rigoletto-freebsd** [mrclksr/linux-browser-installer#35]
I've been experiencing this issue. If I upgrade the `chroot` files, wherever using `linux-browser-installer` or `apt` all browsers fail with that ELF error.

Some time ago, the first time I used this script I had this problem too, I managed to fix it and I could upgrade the `chroot` without breaking anything, but now I have fresh setup and no idea of what I did to fix it.

Is anyone also experiencing this issue?

Thank you.

**Comment by sabazk** [comment]
Me too.  Same issue. Didn't solve it using focal, but by updating `linux-browser-installer` `ubuntu_version=kinetic` and reinstalling the chroot, it works great.
as referenced here #27 

seems it may be related to ld_version?

**Comment by trevarj** [comment]
Just follow [these lines](https://github.com/mrclksr/linux-browser-installer/blob/fea39f5ceb573d843f6a9dbc90afd636806ed7ff/linux-browser-installer#L92-L104C2) to repair the symlink.

This happened to me when I did apt upgrade inside the chroot.

```
$ unlink /compat/ubuntu/lib64/ld-linux-x86-64.so.2
$ cp /compat/ubuntu/lib/x86_64-linux-gnu/ld-2.31.so /compat/ubuntu/lib64/ld-linux-x86-64.so.2
```

**Comment by mrclksr** [comment]
Thanks, @trevarj!
