### ISSUE TITLE
Chrome browser: Netflix error code M7361-1253

### ISSUE THREAD

**Issue by q-pa** [mrclksr/linux-browser-installer#42]
Since 2023-08-24 or -25 I no longer can play content from Netflix (in Germany). The Chrome browser is kept up to date. I also tested lots of different user agents (with user agent switcher). 

OS: GhostBSD

**Comment by ryanavella** [comment]
I'm also seeing the same with Amazon Prime, and it started happening roughly around the same time. (although I did recently upgrade to 13.2)

```sh
$ uname -mrsv
FreeBSD 13.2-RELEASE-p2 FreeBSD 13.2-RELEASE-p2 GENERIC amd64
```

**Comment by q-pa** [comment]
$ uname -mrsv
FreeBSD 13.2-STABLE FreeBSD 13.2-STABLE GENERIC amd64

This is the output of dmesg from /compat/ubuntu:

...
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18275 (ThreadPoolForeg): unsupported TCP socket option TCP_INFO (11)
[    0.000000] linux: jid 0 pid 18409 (dmesg): syslog unsupported type 0xa

**Comment by q-pa** [comment]
I am on GhostBSD and updated my system to `GhostBSD 23.10.1 amd64 ` today

```
$ uname -mrsv
FreeBSD 13.2-STABLE FreeBSD 13.2-STABLE GENERIC amd64
```

At least Netflix is working again, cannot test other DRM-related stuff at the moment.
