### ISSUE TITLE
Does Not Work on 13.2-RELEASE

### ISSUE THREAD

**Issue by vermaden** [mrclksr/linux-browser-installer#44]
Hi,

the DRM videos stopped working after upgrade from FreeBSD 13.1-RELEASE to 13.2-RELEASE.

I am not sure if this is related to Your solution or changes in FreeBSD project.

I can share configs/settings/etc. - just let me know what to send to help.

Regards,
vermaden

**Comment by mrclksr** [comment]
Some change(s) in 13.2-RELEASE are responsible for this problem, but I currently don't have the time to debug it. Everything installs without issues (with or without your proposed solution), but none of the tested streaming sites requiring DRM (Spotify, Prime Video) work on 13.2-RELEASE.
