### ISSUE TITLE
brave-browser not found issue-fixed by installing ca-certificates

### ISSUE THREAD

**Issue by nevillehay** [mrclksr/linux-browser-installer#47]
I ran the install brave script and everything went fine until it was time for the brave-browser package to install. Error message was that brave-browser was not found or something close to that. I then went to the brave website and tried the steps there after chrooting to /compat/ubuntu. Same problem. However I saw in the terminal there was a message that said to install ca-certificates. I did that and everything worked but no menu entry. I then ran the script again but there was a message saying brave-browser is already installed.
So I ran the uninstall script for brave which worked. Then I ran the brave install script and everything is fine. 
Perhaps the install script needs modifying to include the ca-certificates package?

BTW I'm using FreeBSD14.0-RC4.

Thanks very much your hard work and the brave script! Much appreciated

**Comment by mrclksr** [comment]
Thank you for the hint, @nevillehay :-)

**Comment by nevillehay** [comment]
No worries. Thanks for the script
