### ISSUE TITLE
libtinfo.so.6: ELF file OS ABI invalid

### ISSUE THREAD

**Issue by darkoverlordofdata** [mrclksr/linux-browser-installer#48]
I tried upgrading chrome - ./linux-browser-installer chroot upgrade, and got an error
```
ELF interpreter /lib64/ld-linux-x86-64.so.2 not found
```

I thought to reinstall:
```
./linux-browser-installer deinstall chrome
./linux-browser-installer chroot delete
./linux-browser-installer chroot create
./linux-browser-installer install chrome

```

And now I get a new error:
```
linux-chrome                   
/compat/ubuntu/bin/bash: error while loading shared libraries: /usr/local/lib/libtinfo.so.6: ELF file OS ABI invalid
```

**Comment by mrclksr** [comment]
Hi @darkoverlordofdata,

are you using the most recent commit of `linux-browser-installer`? What's your OS version?

**Comment by darkoverlordofdata** [comment]
This is really weird. I had an installed wpa, and I accidentally clicked the icon. I figured it would crash, too. But it worked! Now chrome is working just fine, and upgraded to the new version. I don't get it. But it works!
