### ISSUE TITLE
No sound after update to 14-STABLE

### ISSUE THREAD

**Issue by q-pa** [mrclksr/linux-browser-installer#50]
Updated to OS: GhostBSD 24.01.1 amd64 Kernel: 14.0-STABLE today. Sound generally works in GhostBSD but linux-browser-installer chrome does not play sound anymore.

**Comment by q-pa** [comment]
I would say the commit I installed from is from 2021. 
/compat/ubuntu/var/run is a link.
`lrwxr-xr-x 1 root wheel 4 Dec 13  2021 /compat/ubuntu/var/run -> /run`

**Comment by q-pa** [comment]
Yes! That worked! Many thanks @mrclksr !

**Comment by mrclksr** [comment]
Great! :-)
