### ISSUE TITLE
chrome lost audio again

### ISSUE THREAD

**Issue by hakova** [mrclksr/linux-browser-installer#51]
Hi,

On FreeBSD 14.0-RELEASE-p5, linux-chrome lost its audio output again. Pulseaudio is installed and running, dbus is running as well. However, starting the application either with `linux-chrome` or `/compat/ubuntu/bin/chrome` results in the same error message that is 

`[1927:103507:0319/203948.217471:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory`. However,

`# ll /var/run/dbus/`
`total 10`
`drwxr-xr-x   2 root wheel uarch  4 Mar 19 18:10 ./`
`drwxr-xr-x  15 root wheel uarch 33 Mar 19 18:23 ../`
`-rw-r--r--   1 root wheel uarch  5 Mar 19 18:10 pid`
`srwxrwxrwx   1 root wheel uarch  0 Mar 19 18:10 system_bus_socket=`

Does the equal sign at the end of the dbus socket makes it not recognizable by chrome? 

Restarting the dbus daemon does not solve this problem. Any input will be much appreciated.

**Comment by mrclksr** [comment]
Hi @hakova,

see #50

**Comment by hakova** [comment]
> Hi @hakova,
> 
> see #50

Hi @mrclksr,

I confirm that this works. I am sorry for the noise. Thank you once again for this amazing tool! It has been the mainstay of our family entertainment for more than two years now. Nothing matches it! Special thanks for maintaining it!

**Comment by mrclksr** [comment]
Thank you, @hakova :-)
