### ISSUE TITLE
cannot open rc-ubuntu.tmpl: No such file or directory

### ISSUE THREAD

**Issue by robert-winkler** [mrclksr/linux-browser-installer#57]
Hi, I tried installing the Brave with 
`linux-browser-installer install brave`
This results in the error message:
~~~
cannot open rc-ubuntu.tmpl: No such file or directory
chmod:  /usr/local/etc/rc.d/ubuntu: No such file or directory
linux_enable: NO -> NO
ubuntu_enable: YES -> YES
ubuntu does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
linux-browser-installer: Error: Failed to start ubuntu service
~~~
Any hint?

**Comment by mrclksr** [comment]
Did you try to call the script from outside its directory?

**Comment by robert-winkler** [comment]
Dear @mrclksr, indeed, this was the problem. I started the script from the installation directory, and the installation went smoothly. Thanks a lot!!!
